### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by aopell** [aopell/DiscordBot#1]
- [ ] Way to disable commands
- [x] Proper permissions
- [x] Port to Discord.Net 1.0
- [x] Make command framework better
- [x] ByID should include attachments
- [x] Help command should be improved
- [x] All embeds should use the rich formatting
- [x] Customize prefix
- [x] Better reminder system
- [x] Away/Offline timer
